spring.application.name=fc2-live-automation

# H2データベースをファイルとして保存する設定（./data/fc2db という名前で保存）
spring.datasource.url=jdbc:h2:file:./data/fc2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# アプリ起動時にテーブルを自動更新してデータを引き継ぐ設定
spring.jpa.hibernate.ddl-auto=update